### ISSUE TITLE
UTC Calc Not Handling All Timezones Correctly

### ISSUE THREAD

**Issue by deharlow** [SoliantMike/FM-ZuluTime#1]
When trying to use this for Saipan (+10) the calc does not calculate the correct UTC time.
From the FileMaker Database
![screen shot 2018-06-02 at 4 16 14 pm](https://user-images.githubusercontent.com/33338991/40881648-d919f30c-6680-11e8-98e6-ba1a19bcf343.png)

From https://www.timeanddate.com/worldclock/converter.html
![screen shot 2018-06-02 at 4 18 52 pm](https://user-images.githubusercontent.com/33338991/40881640-b9c60e3c-6680-11e8-956c-b63e073489a2.png)

**Comment by SoliantMike** [comment]
Updated the calculation for this and uploaded new version. Also updated the fields to allow you to select if daylight savings is in effect. You might want to disable the daylight savings auto enter, as it reflects the rules for US daylight savings.
